name: Trello API Tests CI
env:
  KEY: '${{ secrets.KEY }}'
  TOKEN: '${{ secrets.TOKEN }}'
  ID: '${{ secrets.ID }}'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  shcedule:
    cron: '* 3 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.4.0 ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Trello API Test Report
        path: mochawesome-report